local shell = require("shell")
shell.setAlias("sss", "simpleseedsearch.lua")
shell.setAlias("mb", "edit blank.lua")
shell.setAlias("clearfile", "cp blank.lua")
shell.setAlias("ecf" , "edit config.lua")
shell.setAlias("esss" , "edit simpleseedsearch.lua")
shell.setAlias("eut" , "edit util.lua")
shell.setAlias("ecs" , "edit constants.lua")
shell.setAlias("ela", "edit luaaliases.lua")
shell.setAlias("eqh", "edit queryhandler.lua")