---@meta
---@alias cropdata {name:string, tier:integer, resistance:integer, growth:integer, gain:integer}
---@alias data_default {slot:integer, size:integer|nil, cropdata:cropdata|nil}
---@alias data_defaultiter fun():data_default|nil
---@alias querylist string[]
---@alias rawquery string
---@alias bakedquery string
---@alias slotdata_default {slot:integer, size:integer|nil}
---@alias data_ae2 {label:string, size:integer|nil, cropdata:cropdata|nil}
---@alias data_ae2iter fun():data_ae2|nil
---@alias stackdata_ae2 {label:string, size:integer|nil, stackcount:integer|nil}
---@alias direction "up"|"down"|"north"|"south"|"west"|"east"
--wget https://raw.githubusercontent.com/pertiallic/simpleseedsearch_for_oc/main/setup.lua && setup.lua